// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sample_post_beta
double sample_post_beta(NumericVector x, NumericVector y, double tau, double tau_beta);
RcppExport SEXP _rcppBLR_sample_post_beta(SEXP xSEXP, SEXP ySEXP, SEXP tauSEXP, SEXP tau_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_beta(tau_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_post_beta(x, y, tau, tau_beta));
    return rcpp_result_gen;
END_RCPP
}
// sample_post_tau
double sample_post_tau(NumericVector x, NumericVector y, double beta, double a_tau, double d_tau);
RcppExport SEXP _rcppBLR_sample_post_tau(SEXP xSEXP, SEXP ySEXP, SEXP betaSEXP, SEXP a_tauSEXP, SEXP d_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau(a_tauSEXP);
    Rcpp::traits::input_parameter< double >::type d_tau(d_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_post_tau(x, y, beta, a_tau, d_tau));
    return rcpp_result_gen;
END_RCPP
}
// sample_post_beta_arr
double sample_post_beta_arr(NumericVector x, NumericVector y, int n, double tau, double tau_beta);
RcppExport SEXP _rcppBLR_sample_post_beta_arr(SEXP xSEXP, SEXP ySEXP, SEXP nSEXP, SEXP tauSEXP, SEXP tau_betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_beta(tau_betaSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_post_beta_arr(x, y, n, tau, tau_beta));
    return rcpp_result_gen;
END_RCPP
}
// sample_post_tau_arr
double sample_post_tau_arr(NumericVector x, NumericVector y, int n, double beta, double a_tau, double d_tau);
RcppExport SEXP _rcppBLR_sample_post_tau_arr(SEXP xSEXP, SEXP ySEXP, SEXP nSEXP, SEXP betaSEXP, SEXP a_tauSEXP, SEXP d_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau(a_tauSEXP);
    Rcpp::traits::input_parameter< double >::type d_tau(d_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_post_tau_arr(x, y, n, beta, a_tau, d_tau));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_sampler_chain
List gibbs_sampler_chain(NumericVector x, NumericVector y, int n_mcmc, int n_burn, int n_chain, double tau_beta, double a_tau, double d_tau);
RcppExport SEXP _rcppBLR_gibbs_sampler_chain(SEXP xSEXP, SEXP ySEXP, SEXP n_mcmcSEXP, SEXP n_burnSEXP, SEXP n_chainSEXP, SEXP tau_betaSEXP, SEXP a_tauSEXP, SEXP d_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_mcmc(n_mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< int >::type n_chain(n_chainSEXP);
    Rcpp::traits::input_parameter< double >::type tau_beta(tau_betaSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau(a_tauSEXP);
    Rcpp::traits::input_parameter< double >::type d_tau(d_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_sampler_chain(x, y, n_mcmc, n_burn, n_chain, tau_beta, a_tau, d_tau));
    return rcpp_result_gen;
END_RCPP
}
// gamma_sampler
NumericVector gamma_sampler(int n, double shape, double rate);
RcppExport SEXP _rcppBLR_gamma_sampler(SEXP nSEXP, SEXP shapeSEXP, SEXP rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type shape(shapeSEXP);
    Rcpp::traits::input_parameter< double >::type rate(rateSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_sampler(n, shape, rate));
    return rcpp_result_gen;
END_RCPP
}
// gibbs_sampler
List gibbs_sampler(NumericVector x, NumericVector y, int n_mcmc, int n_burn, double init_beta, double init_tau, double tau_beta, double a_tau, double d_tau);
RcppExport SEXP _rcppBLR_gibbs_sampler(SEXP xSEXP, SEXP ySEXP, SEXP n_mcmcSEXP, SEXP n_burnSEXP, SEXP init_betaSEXP, SEXP init_tauSEXP, SEXP tau_betaSEXP, SEXP a_tauSEXP, SEXP d_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_mcmc(n_mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< double >::type init_beta(init_betaSEXP);
    Rcpp::traits::input_parameter< double >::type init_tau(init_tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_beta(tau_betaSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau(a_tauSEXP);
    Rcpp::traits::input_parameter< double >::type d_tau(d_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_sampler(x, y, n_mcmc, n_burn, init_beta, init_tau, tau_beta, a_tau, d_tau));
    return rcpp_result_gen;
END_RCPP
}
// blm
List blm(NumericVector x, NumericVector y, int n_mcmc, int n_burn, int n_chain, double tau_beta, double a_tau, double d_tau);
RcppExport SEXP _rcppBLR_blm(SEXP xSEXP, SEXP ySEXP, SEXP n_mcmcSEXP, SEXP n_burnSEXP, SEXP n_chainSEXP, SEXP tau_betaSEXP, SEXP a_tauSEXP, SEXP d_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_mcmc(n_mcmcSEXP);
    Rcpp::traits::input_parameter< int >::type n_burn(n_burnSEXP);
    Rcpp::traits::input_parameter< int >::type n_chain(n_chainSEXP);
    Rcpp::traits::input_parameter< double >::type tau_beta(tau_betaSEXP);
    Rcpp::traits::input_parameter< double >::type a_tau(a_tauSEXP);
    Rcpp::traits::input_parameter< double >::type d_tau(d_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(blm(x, y, n_mcmc, n_burn, n_chain, tau_beta, a_tau, d_tau));
    return rcpp_result_gen;
END_RCPP
}
// y_post
NumericVector y_post(NumericVector x_new, NumericVector beta_post, NumericVector tau_post);
RcppExport SEXP _rcppBLR_y_post(SEXP x_newSEXP, SEXP beta_postSEXP, SEXP tau_postSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_new(x_newSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_post(beta_postSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau_post(tau_postSEXP);
    rcpp_result_gen = Rcpp::wrap(y_post(x_new, beta_post, tau_post));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rcppBLR_sample_post_beta", (DL_FUNC) &_rcppBLR_sample_post_beta, 4},
    {"_rcppBLR_sample_post_tau", (DL_FUNC) &_rcppBLR_sample_post_tau, 5},
    {"_rcppBLR_sample_post_beta_arr", (DL_FUNC) &_rcppBLR_sample_post_beta_arr, 5},
    {"_rcppBLR_sample_post_tau_arr", (DL_FUNC) &_rcppBLR_sample_post_tau_arr, 6},
    {"_rcppBLR_gibbs_sampler_chain", (DL_FUNC) &_rcppBLR_gibbs_sampler_chain, 8},
    {"_rcppBLR_gamma_sampler", (DL_FUNC) &_rcppBLR_gamma_sampler, 3},
    {"_rcppBLR_gibbs_sampler", (DL_FUNC) &_rcppBLR_gibbs_sampler, 9},
    {"_rcppBLR_blm", (DL_FUNC) &_rcppBLR_blm, 8},
    {"_rcppBLR_y_post", (DL_FUNC) &_rcppBLR_y_post, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_rcppBLR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
