# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_post_beta <- function(x, y, tau, tau_beta) {
    .Call('_rcppBLR_sample_post_beta', PACKAGE = 'rcppBLR', x, y, tau, tau_beta)
}

sample_post_tau <- function(x, y, beta, a_tau, d_tau) {
    .Call('_rcppBLR_sample_post_tau', PACKAGE = 'rcppBLR', x, y, beta, a_tau, d_tau)
}

sample_post_beta_arr <- function(x, y, n, tau, tau_beta) {
    .Call('_rcppBLR_sample_post_beta_arr', PACKAGE = 'rcppBLR', x, y, n, tau, tau_beta)
}

sample_post_tau_arr <- function(x, y, n, beta, a_tau, d_tau) {
    .Call('_rcppBLR_sample_post_tau_arr', PACKAGE = 'rcppBLR', x, y, n, beta, a_tau, d_tau)
}

gibbs_sampler_chain <- function(x, y, n_mcmc, n_burn, n_chain, tau_beta, a_tau, d_tau) {
    .Call('_rcppBLR_gibbs_sampler_chain', PACKAGE = 'rcppBLR', x, y, n_mcmc, n_burn, n_chain, tau_beta, a_tau, d_tau)
}

gamma_sampler <- function(n, shape, rate) {
    .Call('_rcppBLR_gamma_sampler', PACKAGE = 'rcppBLR', n, shape, rate)
}

gibbs_sampler <- function(x, y, n_mcmc, n_burn, init_beta, init_tau, tau_beta, a_tau, d_tau) {
    .Call('_rcppBLR_gibbs_sampler', PACKAGE = 'rcppBLR', x, y, n_mcmc, n_burn, init_beta, init_tau, tau_beta, a_tau, d_tau)
}

blm <- function(x, y, n_mcmc, n_burn, n_chain, tau_beta = 0.001, a_tau = 0.001, d_tau = 0.001) {
    .Call('_rcppBLR_blm', PACKAGE = 'rcppBLR', x, y, n_mcmc, n_burn, n_chain, tau_beta, a_tau, d_tau)
}

y_post <- function(x_new, beta_post, tau_post) {
    .Call('_rcppBLR_y_post', PACKAGE = 'rcppBLR', x_new, beta_post, tau_post)
}

