# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blm <- function(x, y, n_mcmc, n_burn, n_chain, tau_beta = 0.001, a_tau = 0.001, d_tau = 0.001) {
    .Call('_rcppBLR_blm', PACKAGE = 'rcppBLR', x, y, n_mcmc, n_burn, n_chain, tau_beta, a_tau, d_tau)
}

y_post <- function(x_new, beta_post, tau_post) {
    .Call('_rcppBLR_y_post', PACKAGE = 'rcppBLR', x_new, beta_post, tau_post)
}

